# NumPy

In [1]:
import numpy as np

In [2]:
L1 = [1, 2, 3, 4, 5, 6, 7, 8] # crear una lista

In [3]:
x1 = np.array(L1)
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
x2 = np.array(L1, dtype="float32")
x2

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

- bool_
- int_, intc, intp, int8, int16, int32, int64
- uint8, uint16, uint32, uint64
- float_, float16, float32, float64 (+/-9999999999e99999)
- complex_, complex64, complex128 (a+bi, a,b $\in$ float_)

In [5]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(3, 12, dtype=np.float64)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [9]:
np.arange(4, 5, 0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [10]:
np.linspace(1, 7, 12)

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
x.reshape((6, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
x.reshape((3, 8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [15]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [16]:
np.ravel(x) # aplana una matriz

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
np.transpose(x)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [19]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
np.resize(x, (5, 3)) # cuando se queda sin datos los empieza a repetir desde el principio

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

## Ejercicios propuestos

1. Crear un array de datos con valores entre 5 y 120.
2. Crear una matriz 4x4 con valores desde 0 hasta 15.
3. Crear la identidad 7x7.
4. Crear un array de 20 elementos y transformarlos en una matriz 5x4.
5. Crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme.

In [21]:
# Ejercicio 1
np.arange(5, 121)

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120])

In [22]:
# Ejercicio 2
x = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
# Ejercicio 3
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [24]:
# Ejercicio 4
arr = np.arange(20)
arr.reshape((5, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
# Ejercicio 5
np.linspace(0, 5, 20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

# Propiedades de los arrays

In [26]:
x = np.arange(12)
x = x.reshape((3, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
x.ndim # número de dimensiones

2

In [28]:
x.shape

(3, 4)

In [29]:
x.size

12

In [30]:
x.dtype

dtype('int32')

In [31]:
x.itemsize

4

In [32]:
x.data

In [33]:
x[2]

array([ 8,  9, 10, 11])

In [34]:
x[2][1]

9

In [35]:
x.shape = (4, 3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
x[1:3, 0:2]

array([[3, 4],
       [6, 7]])

In [37]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
y[3:8]

array([3, 4, 5, 6, 7])

In [39]:
y[1:7:2]

array([1, 3, 5])

In [40]:
z = np.arange(10, 6, -1)
z

array([10,  9,  8,  7])

In [41]:
y[z]

array([10,  9,  8,  7])

In [42]:
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [43]:
x[x > 30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [44]:
cond = (x < 25)
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [45]:
x[cond]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
x[12:24] = 1
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [47]:
x[13:16] = [6, 9, 12]
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [48]:
x.dtype

dtype('int32')

In [49]:
x[5] = 3.1415
x # no añade los decimales porque se trata de un array de tipo int32

array([ 0,  1,  2,  3,  4,  3,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [50]:
x[8] = 1.2j # no se puede convertir de número complejo a entero, salta error

TypeError: can't convert complex to int

# Copias y vistas de array

In [51]:
x = np.arange(10)

In [52]:
y = x # así se crea una referencia, no una copia

In [53]:
y.shape = (2, 5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
z = x.copy()
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
z is x # z es una copia de x

False

In [57]:
y is x

True

In [58]:
t = x.view()
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
t.shape = (5, 2)
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [60]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
s = x[0:2, 1:3] # esto es una vista
s

array([[1, 2],
       [6, 7]])

In [62]:
s[:] = 5
s

array([[5, 5],
       [5, 5]])

In [63]:
x

array([[0, 5, 5, 3, 4],
       [5, 5, 5, 8, 9]])

In [64]:
y

array([[0, 5, 5, 3, 4],
       [5, 5, 5, 8, 9]])

In [65]:
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Funciones Universales (ufunc)

- Unarias: sqrt, sin, cos, **2
- Binarias: maximum, minimum

In [66]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
x+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [68]:
x-3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [69]:
x*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [70]:
x/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [71]:
alpha = np.linspace(0, 2*np.pi, 4)
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [72]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [73]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [74]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [75]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [76]:
np.exp2(x)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [77]:
np.power(3, x)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683], dtype=int32)

In [78]:
np.power(x, 2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [79]:
np.log(x)

C:\Users\mudar\AppData\Local\Temp\ipykernel_19168\1277889159.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [80]:
np.log2(x)

C:\Users\mudar\AppData\Local\Temp\ipykernel_19168\3275510840.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(x)


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [81]:
np.log10(x)

C:\Users\mudar\AppData\Local\Temp\ipykernel_19168\1114196279.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(x)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

$$\sum_{i=1}^n x_i$$

In [82]:
np.sum(x)

45

In [83]:
np.nansum(x)

45

In [84]:
np.prod(x)

0

In [85]:
np.mean(x)

4.5

In [86]:
np.median(x)

4.5

In [87]:
np.min(x)

0

In [88]:
np.max(x)

9

In [89]:
np.std(x)

2.8722813232690143

In [90]:
np.var(x)

8.25

In [91]:
np.argmin(x) # índice del valor más pequeño

0

In [92]:
np.argmax(x) # índice del valor más grande

9

In [93]:
np.percentile(x, q=0.95)

0.08549999999999999

In [94]:
y = np.array([True, True, True, True])

In [95]:
np.any(y)

True

In [96]:
np.all(y)

True

In [97]:
np.random.seed(2019)
z = np.random.random((3, 5))
z

array([[0.90348221, 0.39308051, 0.62396996, 0.6378774 , 0.88049907],
       [0.29917202, 0.70219827, 0.90320616, 0.88138193, 0.4057498 ],
       [0.45244662, 0.26707032, 0.16286487, 0.8892147 , 0.14847623]])

In [98]:
z.sum()

8.550690063213514

In [99]:
z.sum(axis=0) # suma por columnas

array([1.65510085, 1.3623491 , 1.69004099, 2.40847402, 1.43472509])

In [100]:
z.sum(axis=1) # suma por filas

array([3.43890915, 3.19170818, 1.92007274])